<html lang="pt-br">

<head>
    <?php require '_head.phtml'; ?>
    <title>Calorize</title>

    <script src="/assets/js/application.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body class="flex items-center justify-center min-h-screen bg-gray-100">

    <div class="w-full max-w-sm md:max-w-md bg-white p-6 md:p-8 rounded-lg shadow-md border border-gray-200">
        <div>
            <div class="mb-4">

                <?php require '_flash_message.phtml'; ?>

                <h4 class="text-center text-2xl font-semibold text-gray-800">
                    Login
                </h4>

                <?php require $view ?>
            </div>
        </div>

    </div>

</body>

</html>